#![forbid(unsafe_code)]

include!("context.rs");
include!("args.rs");
include!("dispatch.rs");
include!("cmd/mcp.rs");
include!("cmd/mcp_share.rs");
include!("cmd/web.rs");
include!("cmd/finance/macro_schedule.rs");
include!("cmd/finance/odds.rs");
include!("cmd/finance/options.rs");
include!("cmd/finance/paper.rs");
include!("cmd/finance/ibkr.rs");
include!("cmd/finance/misc.rs");
include!("cmd/finance/timeseries.rs");
include!("cmd/finance/movers.rs");
include!("cmd/finance/movers_extended.rs");
include!("cmd/finance/curve.rs");
include!("cmd/finance/fed.rs");
include!("cmd/finance/mod.rs");
include!("cmd/picks.rs");
